---
title: "Lab2 Instruction"
author: "Jun Cai"
date: "September 18, 2015"
output:
  html_document:
    keep_md: yes
  pdf_document:
    includes:
      in_header: header.tex
    latex_engine: xelatex
---

Lab2 contains basics for file and directory manipulation, and R data input and output. Rather than a complete collection of functions, I will introduce the frequenty-used functions from my own R experience.

Note that all R codes in the following are run on my own Mac OS X. When you try them on your own computer, please customize your own working directory.

## Part I File and Directory Manipulation

`setwd()` and `getwd()`: used to change or determine the current working directory. It's a good habit to set working directory before your data analysis as all results during your data analysis will be stored in the working directory.

`list.files()` and `list.dirs()`: returns a character vector of names of files or directories under the given directory.

`file.info()`: gives file size, creation time, directory vs. ordinary file status, and so on for each file whose name is in the argument, a character vector.

`file.create()` and `dir.create()`: creates files or directories with the given names if they do not already exist.

`file.exists()` and `dir.exists()`: returns a logical vector indicating whether the given file exists for each name in the first argument, a character vector.

`file.copy()` and `file.rename()`: moves files `from` source path `to` destination path. 

`file.remove()` and **`unlink()`**: deletes the files or directories specified by the first argument, a character vector.

```{r}
# set current working directory to DAE
setwd("/Users/tonytsai/Documents/R/DAE")
getwd()

# list all files including directories under current working directory DAE
list.files()
# extract file information for those files
file.info(list.files())
# list only directories under DAE
list.dirs()
# find all R scripts under DAE and give their full path names (or absolute paths)
list.files(recursive = TRUE, pattern = ".R$", full.names = TRUE)

# create a recursive directory under DAE/Lab2, which stores the TXT data 
# that will be read in Part III.
if(!dir.exists("Lab2/data/CMDSSS/SURF_CLI_CHN_MUL_DAY_V3.0"))
  dir.create("Lab2/data/CMDSSS/SURF_CLI_CHN_MUL_DAY_V3.0", recursive = TRUE)

# create a temporary directory under script
if(!dir.exists("script/tmp")) dir.create("script/tmp")
# create a temporary R script under tmp to say Hello World, Hello R!
file.create("script/tmp/tmp.R")
cat("print('Hello World, Hello R!')", file = "script/tmp/tmp.R")
# excute the R script
source("script/tmp/tmp.R")

# copy tmp.R to helloworld.R
file.copy("script/tmp/tmp.R", "script/helloworld.R")
list.files("script", recursive = TRUE)
# rename helloworld.R to hello.R
file.rename("script/helloworld.R", "script/hello.R")
list.files("script", recursive = TRUE)

# delete all R scripts under script directory except for 20150916.R
# attempt to delete inexistent hellworld.R
file.remove(c("script/hello.R", "script/helloworld.R"))
list.files("script", recursive = TRUE)
# delete the temporary directory that is not empty.
unlink("script/tmp", recursive = TRUE)
list.files("script")
```

To see all the file- and directory-related functions, type the following:

```
> ?files
```

## Part II Capturing Results from Console

`print()`

`sink()`

## Part III Imports and Exports

`read.table()`, `write.table()`

`read.csv()`, `write.csv()`

`read.xls()`, `write.xls()`

`load()`, `save()`

`data()`

`read.dbf()`

## References

The following are materials on R data import/export that you can access on the Web.

- [R Data Import/Export](https://cran.r-project.org/doc/manuals/r-release/R-data.html)
